/**
import 'package:soprano/db/entities/entity.dart';

class ConfiguracionEntity implements Entity{

  ConfiguracionEntity(this.map);

  @override
  Map<String, String> map;

  @override
  String get tableName => "configuracion";

  static get sqlCreate => '''
    DROP TABLE IF EXISTS 'configuracion';
  CREATE TABLE 'configuracion' (
    'sContrato' varchar(15) NOT NULL DEFAULT '' COMMENT 'Contrato',
    'sNombre' varchar(70) NOT NULL DEFAULT '' COMMENT 'Nombre',
    'sNombreCorto' varchar(15) NOT NULL COMMENT 'Nombre Corto',
    'sRfc' varchar(15) NOT NULL DEFAULT '*' COMMENT 'RFC',
    'sDireccion1' varchar(255) NOT NULL DEFAULT '*' COMMENT 'Direccion (1)',
    'sDireccion2' varchar(50) NOT NULL DEFAULT '*' COMMENT 'Direccion (2)',
    'sDireccion3' varchar(50) NOT NULL DEFAULT '*' COMMENT 'Direccion (3)',
    'sCiudad' varchar(30) DEFAULT NULL COMMENT 'Cuidad',
    'sSlogan' varchar(100) NOT NULL DEFAULT '*' COMMENT 'Slogan',
    'sPiePagina' varchar(150) NOT NULL DEFAULT '' COMMENT 'Pie de Pagina',
    'bImagen' mediumblob DEFAULT NULL COMMENT 'Imagen',
    'sTelefono' varchar(50) DEFAULT '*' COMMENT 'Telefono',
    'sFax' varchar(50) DEFAULT '*' COMMENT 'Fax',
    'sEmail' varchar(100) NOT NULL DEFAULT '*' COMMENT 'E-Mail',
    'sRepresentanteObra' varchar(60) DEFAULT '' COMMENT 'Reprsentante Onbra',
    'sWeb' varchar(50) NOT NULL DEFAULT '*' COMMENT 'Web',
    'lLicencia' enum('Si','No') NOT NULL DEFAULT 'Si' COMMENT 'Licencia',
    'iRedondeoMaterial' int(2) NOT NULL DEFAULT 2 COMMENT 'Redondeo Material',
    'iRedondeoEquipo' int(2) NOT NULL DEFAULT 2 COMMENT 'Redondeo Equipo',
    'iRedondeoPersonal' int(2) NOT NULL DEFAULT 2 COMMENT 'Redondeo Personal',
    'iRedondeoEmbarcacion' int(2) NOT NULL DEFAULT 16 COMMENT 'Redondeo Embarcacion',
    'sTipoContrato' enum('Tarifa Diaria','Precio Unitario','Precio Unitario x OS','Precio Unitario Gobierno') NOT NULL DEFAULT 'Precio Unitario' COMMENT 'Tipo de Contrato',
    'sRangoEstimacion' enum('Diario','Semanal','Mensual') NOT NULL DEFAULT 'Semanal' COMMENT 'Rango de Estimacion',
    'sTipoPartida' enum('Todas','Anexo C') NOT NULL DEFAULT 'Anexo C' COMMENT 'Tipo de Partida',
    'sDuracion' enum('Horas','Dias') NOT NULL DEFAULT 'Horas' COMMENT 'Duracion',
    'sFolder' varchar(100) NOT NULL DEFAULT '' COMMENT 'Folder',
    'iFirmas' enum('2','3','4') NOT NULL DEFAULT '3' COMMENT 'Firmas',
    'sFirmasElectronicas' enum('2','3') NOT NULL DEFAULT '2' COMMENT 'Firmas Electronicas',
    'sIdConvenio' varchar(5) NOT NULL DEFAULT '' COMMENT 'Convenio',
    'sAnexos' varchar(5) NOT NULL COMMENT 'Anexo',
    'sReportesCIA' varchar(40) NOT NULL DEFAULT 'SUBSEA7',
    'lEnviaCorreo' enum('Si','No') NOT NULL DEFAULT 'No' COMMENT 'Opcion para enviar correos al Autorizar reportes diarios',
    'sFormatos' varchar(500) DEFAULT 'Archivo PDF,Tabla Excel (XML),Imagen JPEG',
    'sSecciones' varchar(400) DEFAULT 'Caratula,Balance General,Avance Global,Notas Generales,Concentrado de Personal,Concentrado de Pernoctas,Concentrado de Equipos,Extraordinaria,Total de Personal,Reporte Fotografico',
    'sSeccionImprime' varchar(350) DEFAULT NULL,
    'iEjercicio' int(11) DEFAULT NULL,
    'lCompanias' enum('Si','No') DEFAULT 'Si',
    'eIva' enum('Si','No') DEFAULT 'No',
    'CtrVersion2018' int(11) DEFAULT NULL,
    'sEjercicioFiltro' varchar(100) DEFAULT NULL,
    'dIVA' float DEFAULT NULL COMMENT 'IVA/Impuesto.',
    'dZoom' float NOT NULL DEFAULT 100 COMMENT 'Zoom Impresion de reportes de Almacén.',
    'lCalculaProrrateo' enum('Pernocta','Personal A Bordo','Personal A Bordo y Tierra') NOT NULL DEFAULT 'Pernocta',
    'EntradaInicio' datetime DEFAULT NULL,
    'EntradaTermino' datetime DEFAULT NULL,
    'SalidaInicio' datetime DEFAULT NULL,
    'SalidaTermino' datetime DEFAULT NULL,
    'BiometricoActivo' enum('Si','No') DEFAULT NULL,
    'VerTodosProyectos' enum('Si','No') DEFAULT 'No',
    'sAlmcon' varchar(20) DEFAULT NULL,
    'sExplosion' enum('Recursos por Concepto/Partida','Analisis de Precio Unitario') NOT NULL DEFAULT 'Recursos por Concepto/Partida',
    'sGenDesp' enum('Normales','Despiezado','Detallado') DEFAULT 'Normales',
    'iFirmasReportes' enum('2','3') NOT NULL DEFAULT '2' COMMENT 'Numero de Firmas para Reportes',
    'iFirmasGeneradores' enum('2','3') NOT NULL DEFAULT '2' COMMENT 'Firma de Generadores de Personal, Equipo, Materiales',
    'iFirmasBarco' enum('2','3') NOT NULL DEFAULT '2' COMMENT 'Numero de Firmas Reporte de Barco',
    'iFirmasEstimaciones' enum('0','2','3','4') NOT NULL DEFAULT '4' COMMENT 'Firmantes de Estimaciones Generales',
    'sLeyenda1' varchar(50) NOT NULL DEFAULT 'POR EL CONTRATISTA\r\nREALIZO' COMMENT 'Leyenda Firmante 1',
    'sLeyenda2' varchar(50) NOT NULL DEFAULT 'POR PEMEX\r\nREVISO' COMMENT 'Leyenda Firmante 2',
    'sLeyenda3' varchar(50) NOT NULL DEFAULT 'POR PEMEX\r\nVo.Bo.' COMMENT 'Leyenda Firmante 3',
    'dCostoDirecto' double(12,3) NOT NULL DEFAULT 0.000 COMMENT 'Costo Directo',
    'dCostoIndirectos' double(12,3) NOT NULL DEFAULT 0.000 COMMENT 'Costos Indirectos',
    'dFinanciamiento' double(12,3) NOT NULL DEFAULT 0.000 COMMENT 'Financiamiento',
    'dUtilidad' double(12,3) NOT NULL DEFAULT 0.000 COMMENT 'Utilidad',
    'dCargosAdicionales' double(12,3) NOT NULL DEFAULT 0.000 COMMENT 'Cargos Adicionales',
    'dCargosAdicionales2' double(12,3) NOT NULL DEFAULT 0.000 COMMENT 'Cargos Adicionales 2',
    'dCargosAdicionales3' double(12,3) NOT NULL DEFAULT 0.000 COMMENT 'Cargos Adicionales 3',
    'lCalculaPU' enum('Si','No') NOT NULL DEFAULT 'No' COMMENT 'Calculo del Precio Unitario',
    'sSimbolo' varchar(2) NOT NULL DEFAULT '*' COMMENT 'Simbolo para la Operacion del Analisis',
    'lOrdenaItem' enum('Si','No') NOT NULL DEFAULT 'No',
    'lImprimeNotasGerenciales' enum('Si','No') DEFAULT 'Si',
    'lImprimeFases' enum('Si','No') DEFAULT 'No',
    'eEstRep' enum('Si','No') DEFAULT 'No',
    'dIndCampo' double(13,3) NOT NULL DEFAULT 0.000,
    'dIndOficina' double(13,3) NOT NULL DEFAULT 0.000,
    'dFsobreCosto' double(13,3) NOT NULL DEFAULT 1.000,
    'dFIndirecto' double(13,3) NOT NULL DEFAULT 1.000 COMMENT 'Porcentaje de Infirecto a descontar del Contrato',
    'iJLunes' decimal(4,2) NOT NULL DEFAULT 8.00 COMMENT 'Lunes',
    'iJMartes' decimal(4,2) NOT NULL DEFAULT 8.00 COMMENT 'Martes',
    'iJMiercoles' decimal(4,2) NOT NULL DEFAULT 8.00 COMMENT 'Miercoles',
    'iJJueves' decimal(4,2) NOT NULL DEFAULT 8.00 COMMENT 'Jueves',
    'iJViernes' decimal(4,2) NOT NULL DEFAULT 8.00 COMMENT 'Viernes',
    'iJSabado' decimal(4,2) NOT NULL DEFAULT 8.00 COMMENT 'Sabado',
    'iJDomingo' decimal(4,2) NOT NULL DEFAULT 8.00 COMMENT 'Domingo',
    'sImprimePaqSub' enum('SI','NO') NOT NULL DEFAULT 'SI',
    'cStatusProceso' char(1) NOT NULL DEFAULT 'P' COMMENT 'Status Proceso',
    'cStatusSuspendida' char(1) NOT NULL DEFAULT 'S' COMMENT 'Status Suspendida',
    'cStatusTerminada' char(1) NOT NULL DEFAULT 'T' COMMENT 'Status Terminada',
    'sIdDepartamento' varchar(4) NOT NULL DEFAULT '' COMMENT '/*Departamento',
    'sIdEmbarcacion' varchar(10) NOT NULL DEFAULT '*' COMMENT '/*Embarcacion',
    'sRangoAjusteMenor' varchar(13) NOT NULL DEFAULT '' COMMENT 'Rango Ajuste Menor',
    'sRangoAjusteMayor' varchar(13) NOT NULL DEFAULT '' COMMENT 'Rango Ajuste Mayor',
    'lCalculaFecha' enum('Si','No') NOT NULL DEFAULT 'No' COMMENT 'Calcular Fecha ?',
    'sTipoOperacion' varchar(4) NOT NULL DEFAULT 'E' COMMENT 'Tipo de Operacion',
    'sTipoAlcance' varchar(4) NOT NULL DEFAULT 'A' COMMENT 'Tipo de Alcance',
    'sTipoCIA' varchar(4) NOT NULL DEFAULT '' COMMENT 'Tipo CIA',
    'lAutomatico' enum('Si','No') NOT NULL DEFAULT 'Si' COMMENT 'Automatico',
    'iIncremento' int(2) NOT NULL DEFAULT 0 COMMENT 'Incremento',
    'sReporteDiario' varchar(100) NOT NULL DEFAULT '' COMMENT 'Reporte Diario',
    'sGerencial' varchar(100) NOT NULL DEFAULT '' COMMENT 'Gerencial',
    'sIsometricos' varchar(100) NOT NULL DEFAULT '' COMMENT 'Isometrico',
    'sHost' varchar(100) NOT NULL DEFAULT '' COMMENT 'Host',
    'sViewIsometrico' enum('AutoCad','Acrobat') NOT NULL DEFAULT 'AutoCad' COMMENT 'Visor de Isometrico',
    'lExporta' enum('Si','No') NOT NULL DEFAULT 'Si' COMMENT 'Exporta ?',
    'sIdPernocta' varchar(10) NOT NULL DEFAULT '' COMMENT 'Pernocta',
    'lTiempoMuertoTurnos' enum('Si','No') NOT NULL DEFAULT 'No' COMMENT 'Calcula Tiempo Muerto aplicando el personal afectado a dos turnos.. Nuevo Calculo.',
    'sSeguridadGenerador' enum('Con Seguridad','Sin Seguridad') NOT NULL DEFAULT 'Con Seguridad' COMMENT 'Seguridad en el Generador',
    'lAplicaAvisosGen' enum('Si','No') NOT NULL DEFAULT 'Si' COMMENT 'Aplica avisos de embarque generadores',
    'lAplicaAvisos' enum('Si','No') NOT NULL DEFAULT 'Si' COMMENT 'Aplica avisos de embarque',
    'lCalculoPonderado' enum('Duracion','Financiero','Mezcla') NOT NULL DEFAULT 'Duracion' COMMENT 'Calculo Ponderado',
    'sTipoAjusteCosto' enum('Normal','Extendido') NOT NULL DEFAULT 'Extendido' COMMENT 'Tipo de Ajuste de Costo',
    'sTerminoPenalizacion' enum('Reportes Diarios','Generadores de Obra') NOT NULL DEFAULT 'Reportes Diarios' COMMENT 'Termino Penalizacion',
    'sImporteRetencion' enum('Solo Generadores Normales','Todos los Generadores') NOT NULL DEFAULT 'Todos los Generadores' COMMENT 'Importe de Retencion',
    'sBaseCalculo' enum('Mensual','Acumulado') NOT NULL DEFAULT 'Mensual' COMMENT 'Base Calculo',
    'dRetencion' decimal(5,3) NOT NULL DEFAULT 0.000 COMMENT 'Retencion',
    'dPenaConvencional' double(7,5) NOT NULL DEFAULT 0.00000 COMMENT 'Pena Convencional',
    'bImagen2' mediumblob DEFAULT NULL,
    PRIMARY KEY ('sContrato'),
    KEY 'a_fk_001' ('sAnexos'),
    KEY 'con_fk_013' ('sContrato','sIdConvenio')
  ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Configuración del Sistema';
  ''';
}*/*/*/