/**
import 'package:soprano/db/entities/entity.dart';

class FirmasEntity implements Entity{

  FirmasEntity(this.map);

  @override
  Map<String, String> map;

  @override
  String get tableName => "firmas";

  static get sqlCreate => '''
  DROP TABLE IF EXISTS 'firmas';
  CREATE TABLE 'firmas' (
    'sContrato' varchar(15) NOT NULL DEFAULT '' COMMENT 'Contrato',
    'sIdTurno' char(2) NOT NULL DEFAULT 'A' COMMENT 'Turno',
    'IdDepartamento' int(11) DEFAULT NULL,
    'dIdFecha' date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha',
    'sNumeroOrden' varchar(35) NOT NULL DEFAULT '' COMMENT '/*Numero de Orden',
    'sFirmante1' varchar(60) NOT NULL DEFAULT '' COMMENT 'Representante de la Compañia',
    'sFirmante2' varchar(60) NOT NULL DEFAULT '' COMMENT 'Representante Tecnico',
    'sFirmante3' varchar(60) NOT NULL DEFAULT '' COMMENT 'Sup. Cia. Patio',
    'sFirmante4' varchar(60) NOT NULL DEFAULT '' COMMENT 'Representante de la Subcontratista',
    'sFirmante5' varchar(60) NOT NULL DEFAULT '' COMMENT 'Revisa Reportes Diarios/Estimaciones',
    'sFirmante6' varchar(60) NOT NULL DEFAULT '' COMMENT 'Autoriza Reportes Diarios/Generadores/Estimaciones',
    'sFirmante7' varchar(60) NOT NULL DEFAULT '' COMMENT 'Revisa Generadores de Obra',
    'sFirmante8' varchar(60) NOT NULL DEFAULT '' COMMENT 'Residente de ObraRevisa Generadores de Obra',
    'sFirmante9' varchar(60) NOT NULL DEFAULT '' COMMENT 'Revisa Resumenes de Generadores',
    'sFirmante10' varchar(60) NOT NULL DEFAULT '' COMMENT 'Sub. Obra Patio',
    'sFirmante11' varchar(60) NOT NULL DEFAULT '' COMMENT 'Representante de la Compañia',
    'sFirmante12' varchar(60) NOT NULL DEFAULT '' COMMENT 'Representante Tecnico',
    'sFirmante13' varchar(60) NOT NULL DEFAULT '' COMMENT 'Sup. Cia. Patio',
    'sFirmante14' varchar(60) NOT NULL DEFAULT '' COMMENT 'Representante de la Subcontratista',
    'sFirmante15' varchar(60) NOT NULL DEFAULT '' COMMENT 'Revisa Reportes Diarios/Estimaciones',
    'sFirmante16' varchar(60) NOT NULL DEFAULT '' COMMENT 'Autoriza Reportes Diarios/Generadores/Estimaciones',
    'sFirmante17' varchar(60) NOT NULL DEFAULT '' COMMENT 'Revisa Generadores de Obra',
    'sFirmante18' varchar(60) NOT NULL DEFAULT '' COMMENT 'Residente de ObraRevisa Generadores de Obra',
    'sFirmante19' varchar(60) DEFAULT '' COMMENT 'Firmante de Estimaciones Generales 1',
    'sFirmante20' varchar(60) DEFAULT '' COMMENT 'Firmante de Estimaciones Generales 2',
    'sFirmante21' varchar(60) DEFAULT '' COMMENT 'Firmante de Estimaciones Generales 3',
    'sFirmante22' varchar(60) DEFAULT '' COMMENT 'Firmante de Estimaciones Generales 4',
    'sFirmante23' varchar(60) DEFAULT '*' COMMENT '1.- Reporte de Campo',
    'sFirmante24' varchar(60) DEFAULT '*' COMMENT '2.- Firmante Reporte Diario',
    'sFirmante25' varchar(60) DEFAULT '*' COMMENT '3.- Firmante de Reporte de Campo',
    'sFirmante26' varchar(60) DEFAULT '*',
    'sFirmante27' varchar(60) DEFAULT '*',
    'sFirmante28' varchar(60) DEFAULT '*',
    'sFirmante29' varchar(60) DEFAULT '*',
    'sPuesto1' varchar(80) NOT NULL DEFAULT '' COMMENT 'Puesto Representante de la Compañia',
    'sPuesto2' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Representante Tecnico',
    'sPuesto3' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Sup. Cia. Patio',
    'sPuesto4' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Representante de la Subcontratista',
    'sPuesto5' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Revisa Reportes Diarios/Estimaciones',
    'sPuesto6' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Autoriza Reportes Diarios/Generadores/Estimaciones',
    'sPuesto7' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Revisa Generadores de Obra',
    'sPuesto8' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Residente de Obra',
    'sPuesto9' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Revisa Resumenes de Generadores',
    'sPuesto10' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Sub. Obra Patio',
    'sPuesto11' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Representante de la Compañia',
    'sPuesto12' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Representante Tecnico',
    'sPuesto13' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Sup. Cia. Patio',
    'sPuesto14' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Representante de la Subcontratista',
    'sPuesto15' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Revisa Reportes Diarios/Estimaciones',
    'sPuesto16' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Autoriza Reportes Diarios/Generadores/Estimaciones',
    'sPuesto17' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Revisa Generadores de Obra',
    'sPuesto18' varchar(70) NOT NULL DEFAULT '' COMMENT 'Puesto Residente de Obra',
    'sPuesto19' varchar(70) DEFAULT '' COMMENT 'Puesto del firmante de Estimaciones Generales 1',
    'sPuesto20' varchar(70) DEFAULT '' COMMENT 'Puesto del firmante de Estimaciones Generales 2',
    'sPuesto21' varchar(70) DEFAULT '' COMMENT 'Puesto del firmante de Estimaciones Generales 3',
    'sPuesto22' varchar(70) DEFAULT '' COMMENT 'Puesto del firmante de Estimaciones Generales 4',
    'sPuesto23' varchar(70) DEFAULT '*' COMMENT '1.- Puesto Reporte de Campo',
    'sPuesto24' varchar(70) DEFAULT '*' COMMENT '2.- Puesto Reporte de Campo',
    'sPuesto25' varchar(70) DEFAULT '*' COMMENT '3.- Puesto Reporte de Campo',
    'sPuesto26' varchar(70) DEFAULT NULL,
    'sPuesto27' varchar(70) DEFAULT NULL,
    'sPuesto28' varchar(70) DEFAULT NULL,
    'sPuesto29' varchar(70) DEFAULT NULL,
    'sFirmante30' varchar(60) DEFAULT NULL,
    'sPuesto30' varchar(70) DEFAULT NULL,
    'sFirmante31' varchar(70) NOT NULL DEFAULT '' COMMENT 'Nombre del capitan',
    'bCostosSub' enum('0','1') NOT NULL DEFAULT '1' COMMENT 'Muestra control de Costos',
    'iCostosSub' int(5) NOT NULL DEFAULT 8 COMMENT 'Fila Inicia Control Costos',
    'bCostosAdmon' enum('0','1') NOT NULL DEFAULT '1' COMMENT 'Muestra Control de Costos Admon',
    'iCostosAdmon' int(5) NOT NULL DEFAULT 16 COMMENT 'Fila inicia costos admon ',
    'sComentario1' varchar(100) NOT NULL DEFAULT 'ASPECTOS IMPORTANTES:' COMMENT 'Descripcion del comentario',
    'iComentario1' int(5) NOT NULL DEFAULT 50 COMMENT 'Inicia comentario en Fila. No.',
    'sComentario2' varchar(100) NOT NULL DEFAULT 'CAUSAS DE LA DESVIACIÓN:',
    'iComentario2' int(5) NOT NULL DEFAULT 63,
    'sComentario3' varchar(100) NOT NULL DEFAULT 'ACCIONES CORRECTIVAS:',
    'iComentario3' int(5) NOT NULL DEFAULT 70,
    'sComentario4' varchar(100) NOT NULL DEFAULT 'ACTIVIDADES EJECUTADAS EN EL PERÍODO: ',
    'iComentario4' int(5) NOT NULL DEFAULT 8,
    'sComentario5' varchar(100) NOT NULL DEFAULT 'ACTIVIDADES PLANIFICADAS NO INICIADAS EN EL PERÍODO: ',
    'iComentario5' int(5) NOT NULL DEFAULT 26,
    'sComentario6' varchar(100) NOT NULL DEFAULT 'ACTIVIDADES PLANIFICADAS PARA EL PRÓXIMO PERÍODO:',
    'iComentario6' int(5) NOT NULL DEFAULT 38,
    'sComentario7' varchar(100) NOT NULL DEFAULT 'ACTIVIDADES PROGRAMADAS PARA EL PRÓXIMO PERÍODO:',
    'iComentario7' int(5) NOT NULL DEFAULT 57,
    'sComentario8' varchar(100) NOT NULL DEFAULT '',
    'iComentario8' int(5) NOT NULL DEFAULT 60,
    PRIMARY KEY ('sContrato','dIdFecha','sNumeroOrden','sIdTurno'),
    KEY 'firmas_fk' ('sContrato','sNumeroOrden'),
    KEY 'md_fk_007' ('IdDepartamento'),
    CONSTRAINT 'md_fk_007' FOREIGN KEY ('IdDepartamento') REFERENCES 'master_departamento' ('IdDepartamento') ON UPDATE CASCADE,
    CONSTRAINT 'ot_fk_042' FOREIGN KEY ('sContrato', 'sNumeroOrden') REFERENCES 'ordenesdetrabajo' ('sContrato', 'sNumeroOrden') ON UPDATE CASCADE,
    CONSTRAINT 'pro_fk_111' FOREIGN KEY ('sContrato') REFERENCES 'rd_proyectos' ('sContrato') ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Firmantes del día';
  ''';
}*/*/